name: toxsmi
channels:
 - https://conda.anaconda.org/rdkit
dependencies:
  - rdkit=2019.03.1
  - python>=3.6,<3.8
  - pip>=19.1
  - pip:
    - pytoda @ git+https://github.com/PaccMann/paccmann_datasets@0.1.1
    - paccmann_predictor @ git+https://github.com/PaccMann/paccmann_predictor@0.0.2  
    - numpy>=1.14.3
    - torch==1.5.1
    - deepchem>=2.4
    - six==1.15.0
    - scikit-learn==0.21.3
    - tensorflow>=2.0
    - Pillow==7.1.0

